"""add cancellation reason to bookings

Revision ID: a8ea38400103
Revises: 9a9341dea320
Create Date: 2026-07-07 01:04:37.429913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ea38400103'
down_revision: Union[str, Sequence[str], None] = '9a9341dea320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'cancellation_reason')
    # ### end Alembic commands ###
