"""add adult/child availability flags to services

Revision ID: b864566a729d
Revises: a8ea38400103
Create Date: 2026-07-12 16:39:53.110330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b864566a729d'
down_revision: Union[str, Sequence[str], None] = 'a8ea38400103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('available_for_adult', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('services', sa.Column('available_for_child', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'available_for_child')
    op.drop_column('services', 'available_for_adult')
    # ### end Alembic commands ###
